BEGIN;

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS assigned_to text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_customers_assigned_to'
  ) THEN
    ALTER TABLE customers
      ADD CONSTRAINT fk_customers_assigned_to
      FOREIGN KEY (assigned_to)
      REFERENCES app_users(user_id)
      ON DELETE SET NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_customers_assigned_to
  ON customers (assigned_to, company, customer_id);

CREATE TABLE IF NOT EXISTS customer_assignment_history (
  assignment_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  previous_assigned_to text,
  assigned_to text,
  changed_by text,
  reason text,
  assigned_at timestamptz NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_customer_assignment_history_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_customer_assignment_history_previous_user
    FOREIGN KEY (previous_assigned_to)
    REFERENCES app_users(user_id)
    ON DELETE SET NULL,
  CONSTRAINT fk_customer_assignment_history_assigned_user
    FOREIGN KEY (assigned_to)
    REFERENCES app_users(user_id)
    ON DELETE SET NULL,
  CONSTRAINT fk_customer_assignment_history_changed_by
    FOREIGN KEY (changed_by)
    REFERENCES app_users(user_id)
    ON DELETE SET NULL,
  CONSTRAINT chk_customer_assignment_history_change
    CHECK (previous_assigned_to IS DISTINCT FROM assigned_to)
);

CREATE INDEX IF NOT EXISTS idx_customer_assignment_history_customer_time
  ON customer_assignment_history (
    customer_id,
    assigned_at DESC,
    assignment_history_id DESC
  );

UPDATE customers
SET assigned_to = created_by
WHERE assigned_to IS NULL
  AND created_by IS NOT NULL;

INSERT INTO customer_assignment_history (
  customer_id,
  previous_assigned_to,
  assigned_to,
  changed_by,
  reason,
  assigned_at
)
SELECT
  c.customer_id,
  NULL,
  c.assigned_to,
  c.created_by,
  'Initial ownership backfill',
  COALESCE(c.created_at, NOW())
FROM customers c
WHERE c.assigned_to IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM customer_assignment_history cah
    WHERE cah.customer_id = c.customer_id
  );

COMMIT;
