import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Tooltip, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add"; import EditIcon from "@mui/icons-material/Edit"; import EmailIcon from "@mui/icons-material/Email"; import RefreshIcon from "@mui/icons-material/Refresh";
import api from "../services/api"; import { useAuth } from "../context/AuthContext";
const roles=["admin","manager","sales","technician","viewer"];
const empty={UserID:"",FullName:"",Email:"",Role:"viewer"};
const color=s=>s==="active"?"success":s==="invited"?"info":s==="expired"?"warning":"default";
const when=v=>v?new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
export default function Users(){
 const {user}=useAuth();const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [open,setOpen]=useState(false),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[editRole,setEditRole]=useState("viewer");const admin=user?.role==="admin";
 async function load(){try{setLoading(true);setError("");const r=await api.get("/admin/users");setRows(Array.isArray(r.data)?r.data:[]);}catch(e){setError(e.response?.data?.message||"Unable to load users.");}finally{setLoading(false);}}
 useEffect(()=>{admin?load():setLoading(false)},[admin]);const sorted=useMemo(()=>[...rows].sort((a,b)=>String(a.full_name||a.email).localeCompare(String(b.full_name||b.email))),[rows]);
 const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value}));
 async function invite(e){e.preventDefault();try{setSaving(true);setError("");const r=await api.post("/admin/users/invite",form);setSuccess(r.data.message||"Invitation sent.");setOpen(false);setForm(empty);await load();}catch(x){setError(x.response?.data?.message||"Unable to send invitation.");}finally{setSaving(false);}}
 async function resend(row){try{setSaving(true);setError("");const r=await api.post(`/admin/users/${encodeURIComponent(row.user_id)}/resend-invitation`);setSuccess(r.data.message||"Invitation resent.");await load();}catch(x){setError(x.response?.data?.message||"Unable to resend invitation.");}finally{setSaving(false);}}
 async function saveRole(){try{setSaving(true);await api.patch(`/admin/users/${encodeURIComponent(editing.user_id)}`,{Role:editRole});setSuccess("User role updated.");setEditing(null);await load();}catch(x){setError(x.response?.data?.message||"Unable to update user.");}finally{setSaving(false);}}
 async function deactivate(row){try{setSaving(true);await api.patch(`/admin/users/${encodeURIComponent(row.user_id)}`,{IsActive:false});setSuccess("User deactivated.");await load();}catch(x){setError(x.response?.data?.message||"Unable to deactivate user.");}finally{setSaving(false);}}
 if(!admin)return <Alert severity="error">Administrator access is required.</Alert>;
 return <Stack spacing={2.5}><Paper sx={{p:2.5}}><Stack direction={{xs:"column",sm:"row"}} spacing={2} justifyContent="space-between" alignItems={{xs:"stretch",sm:"center"}}><Box><Typography variant="h5" sx={{fontWeight:700}}>Users</Typography><Typography color="text.secondary">Invite users by email and manage their roles.</Typography></Box><Stack direction="row" spacing={1}><Tooltip title="Refresh"><span><IconButton onClick={load} disabled={loading}><RefreshIcon/></IconButton></span></Tooltip><Button variant="contained" startIcon={<AddIcon/>} onClick={()=>setOpen(true)}>Invite user</Button></Stack></Stack></Paper>
 {error&&<Alert severity="error">{error}</Alert>}{success&&<Alert severity="success">{success}</Alert>}
 <Paper><TableContainer>{loading?<Box sx={{minHeight:260,display:"grid",placeItems:"center"}}><CircularProgress/></Box>:<Table size="small"><TableHead><TableRow><TableCell>User</TableCell><TableCell>Role</TableCell><TableCell>Status</TableCell><TableCell>Invitation expiry</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{sorted.map(r=><TableRow key={r.user_id} hover><TableCell><Typography variant="body2" sx={{fontWeight:700}}>{r.full_name}</Typography><Typography variant="caption" color="text.secondary" sx={{display:"block"}}>{r.email}</Typography><Typography variant="caption" color="text.secondary">{r.user_id}</Typography></TableCell><TableCell>{r.role}</TableCell><TableCell><Chip size="small" label={r.invitation_status} color={color(r.invitation_status)}/></TableCell><TableCell>{when(r.invitation_expires_at)}</TableCell><TableCell align="right"><Tooltip title="Edit role"><IconButton size="small" onClick={()=>{setEditing(r);setEditRole(r.role)}}><EditIcon/></IconButton></Tooltip>{!r.is_active&&<Tooltip title="Resend invitation"><span><IconButton size="small" disabled={saving} onClick={()=>resend(r)}><EmailIcon/></IconButton></span></Tooltip>}{r.is_active&&r.user_id!==user?.userId&&<Button size="small" color="error" disabled={saving} onClick={()=>deactivate(r)}>Deactivate</Button>}</TableCell></TableRow>)}{!sorted.length&&<TableRow><TableCell colSpan={5} align="center" sx={{py:5}}>No users found.</TableCell></TableRow>}</TableBody></Table>}</TableContainer></Paper>
 <Dialog open={open} onClose={()=>!saving&&setOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={invite}><DialogTitle>Invite user</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{pt:1}}><Alert severity="info">The user receives a one-time link and creates their own password.</Alert><TextField label="User ID" name="UserID" value={form.UserID} onChange={change} required autoFocus/><TextField label="Full name" name="FullName" value={form.FullName} onChange={change} required/><TextField label="Email" name="Email" type="email" value={form.Email} onChange={change} required/><TextField select label="Role" name="Role" value={form.Role} onChange={change}>{roles.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)} disabled={saving}>Cancel</Button><Button type="submit" variant="contained" disabled={saving}>{saving?"Sending...":"Send invitation"}</Button></DialogActions></Box></Dialog>
 <Dialog open={Boolean(editing)} onClose={()=>!saving&&setEditing(null)} fullWidth maxWidth="xs"><DialogTitle>Edit user role</DialogTitle><DialogContent dividers><TextField select fullWidth label="Role" value={editRole} onChange={e=>setEditRole(e.target.value)}>{roles.map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></DialogContent><DialogActions><Button onClick={()=>setEditing(null)} disabled={saving}>Cancel</Button><Button variant="contained" onClick={saveRole} disabled={saving}>Save</Button></DialogActions></Dialog>
 </Stack>;
}
